#!/usr/bin/env python3
"""Build the Sheffield map, and write its pins into the page.

    python3 build_sheffield_map.py sheffield.html sheffield-map.svg \
        rivers.json major-roads.json residential.json

A FORK OF build_city_map.py, PENDING A DECISION
This is the same program with three changes, kept separate so naples.html
cannot be broken while the changes are being looked at. Merging the two is
the better end state; see the note in my message.

  1. INLAND. Naples has a coastline, so its land is found by flooding the sea
     from a point known to be water and tracing what is left. Sheffield has no
     coastline in the frame, so there is nothing to flood and nothing to trace:
     the land is the whole rectangle, and it is emitted as a <rect>. That also
     drops the potrace dependency for this city.

  2. OVERPASS JSON, NOT GEOJSON. overpass-turbo hands you GeoJSON; the API
     hands you Overpass JSON, where a way carries a flat "geometry" list of
     {lat, lon} and its tags sit under "tags". Reading that directly was
     cheaper than asking for a conversion step that can go wrong quietly.

  3. SEVERAL FILES IN. The three queries had to be run separately because the
     server kept timing out on the combined one, so the reader takes any
     number of files and concatenates their elements.
"""

import sys, re, math, html, json
import numpy as np, cv2

PAGE    = sys.argv[1]
OUT_SVG = sys.argv[2]
INPUTS  = sys.argv[3:]

# The frame, in coordinates. Chosen to hold the centre, Kelham, Sharrow and
# Nether Edge, and to come out at Naples' proportions so the two city maps sit
# identically on the page. The height follows from the width and the
# projection; do not set it.
W_DEG, E_DEG = -1.52700, -1.46150
S_DEG, N_DEG = 53.35750, 53.41050
PXW = 1400

INK   = '#000000'                  # --ink
ROAD_MAJOR = '#5f5f5f'
ROAD_MINOR = '#3a3a3a'
ACCENT     = '#c4362b'             # --accent, the locator rectangle
RIVER      = '#f4f1ea'             # --band, i.e. read as water

# Rendered thinnest first so the big roads cross over the small ones.
#
# WHY unclassified AND pedestrian ARE HERE AND service IS NOT
# Central Sheffield is barely tagged residential -- 26 ways inside the ring
# road against 1,570 across the frame -- so the first build drew the city
# centre as a hole. The streets are there, under `unclassified` mostly, with
# the Devonshire Green and Fargate precincts under `pedestrian`. Both are drawn
# a shade thinner than residential: they are the finest grain the map carries.
# `service` was left out on purpose; it is every car park aisle and back alley
# in the frame, and at this size that is noise rather than texture.
ROADS = [('pedestrian',  1.3, ROAD_MINOR),
         ('residential', 1.6, ROAD_MINOR),
         ('unclassified',1.6, ROAD_MINOR),
         ('tertiary',    2.4, ROAD_MINOR),
         ('secondary',   3.5, ROAD_MAJOR),
         ('primary',     5.0, ROAD_MAJOR),
         ('trunk',       6.0, ROAD_MAJOR),
         ('motorway',    7.0, ROAD_MAJOR)]

# Two widths, on the same argument as the two road greys. The Don and the Sheaf
# are structure; the Porter and the brooks are texture. The goits and mill
# races arrive tagged as streams and are drawn as streams -- whether they earn
# a line of their own is still open.
WATER = [('stream', 2.2), ('river', 4.0)]

# The centre window: the second map, and the rectangle drawn on the first.
# Sized so it still magnifies at half the page width -- a wider window at
# side-by-side size is barely more zoomed than the city map, which defeats it.
CW_DEG, CE_DEG = -1.48000, -1.46500
CS_DEG, CN_DEG = 53.37620, 53.38980
CPXW = 1100

FLIP_ABOVE = 18                    # per cent of the frame height
SIMPLIFY   = 1.2                   # px

FENCES = {'CITY':   ('<!-- PINS-CITY: generated by build_sheffield_map.py, do not edit by hand -->',
                     '<!-- /PINS-CITY -->'),
          'CENTRE': ('<!-- PINS-CENTRE: generated by build_sheffield_map.py, do not edit by hand -->',
                     '<!-- /PINS-CENTRE -->')}

# Names must match the .spot-name text on the page exactly; the script reports
# both directions of mismatch. Thirteen of the twenty-five are still to come, so thirteen
# numbers are missing from the map — the counters are shared with the rows, so
# the gaps are the rows that have no coordinate rather than a numbering fault.
COORDS = {
    'The Grapes':              (53.381952458543594, -1.4749353163576204),
    'The Three Tuns':          (53.38398808780298,  -1.4712816116473153),
    "Fagan's":                 (53.383270485462454, -1.4762733558204233),
    'The Washington':          (53.37905341726807,  -1.4782882022782815),
    'The Nottingham House':    (53.37868020026007,  -1.498780727061972),
    'Best Boy Bagels':         (53.360841455224936, -1.4794858134941944),
    'Nam Song':                (53.37756469272776,  -1.5006198576718308),
    'Napoli Centro':           (53.37886377210822,  -1.4897646335529282),
    'Pellizco':                (53.36748681302443,  -1.4971481721204025),
    'the Orange Bird':         (53.404461887355744, -1.503337587459579),
    'Bakers Yard Bakery':      (53.38862957846721,  -1.4723082539767784),
    '2323 Coffee':             (53.38124638985069,  -1.4685083153410738),
    "Mow's Coffee":            (53.37752717980643,  -1.4676326660304164),
    'Depot Bakery':            (53.40738959484458,  -1.5029949586240015),
    'Husk':                    (53.37257267350523,  -1.477392208325515),
    'Bear Tree Records':       (53.37932039808407,  -1.4772328576705374),
    'La Biblioteka':           (53.380057274336366, -1.4726549512335896),
    'Good Good Vintage':       (53.38069173609666,  -1.4742057555153725),
    'Pipers Artisan Sausages': (53.379301553772066, -1.520965196398985),
}

merc = lambda lat: math.log(math.tan(math.pi/4 + math.radians(lat)/2))


class Frame:
    """One map: its window in degrees, its size in pixels, its projection."""

    def __init__(self, w, e, s, n, pxw):
        self.w, self.e, self.s, self.n, self.pxw = w, e, s, n, pxw
        self.sx = pxw / (math.radians(e) - math.radians(w))
        self.pxh = int(round(self.sx * (merc(n) - merc(s))))

    def px(self, lon, lat):
        return (self.sx*(math.radians(lon) - math.radians(self.w)),
                self.sx*(merc(self.n) - merc(lat)))

    def holds(self, lat, lon):
        return self.s <= lat <= self.n and self.w <= lon <= self.e


CITY   = Frame(W_DEG, E_DEG, S_DEG, N_DEG, PXW)
CENTRE = Frame(CW_DEG, CE_DEG, CS_DEG, CN_DEG, CPXW)


def load(paths):
    """Every way from every file, as (tags, [(lon, lat), ...])."""
    out = []
    for p in paths:
        els = json.load(open(p))['elements']
        for e in els:
            if e.get('type') != 'way' or 'geometry' not in e:
                continue
            out.append((e.get('tags', {}),
                        [(g['lon'], g['lat']) for g in e['geometry']]))
        print('  %-22s %5d ways' % (p.split('/')[-1], len(els)))
    return out


def lines_path(fr, ways, key, value):
    """One path for every way of a class, simplified and clipped."""
    pad, segs = 40, []
    for tags, coords in ways:
        if tags.get(key) != value:
            continue
        pts = np.array([fr.px(x, y) for x, y in coords], np.float32)
        if (pts[:, 0].max() < -pad or pts[:, 0].min() > fr.pxw+pad or
            pts[:, 1].max() < -pad or pts[:, 1].min() > fr.pxh+pad):
            continue                           # wholly outside the frame
        pts = cv2.approxPolyDP(pts.reshape(-1, 1, 2), SIMPLIFY, False).reshape(-1, 2)
        if len(pts) < 2:
            continue
        segs.append('M' + 'L'.join('%.1f,%.1f' % (x, y) for x, y in pts))
    return ''.join(segs), len(segs)


def stroke(colour, width, d):
    return ('<path fill="none" stroke="%s" stroke-width="%s" '
            'stroke-linecap="round" stroke-linejoin="round" d="%s"/>'
            % (colour, width, d))


def read_places(page):
    src = open(page).read()
    out = []
    for sec, block in re.findall(r'<section class="module" id="(\w+)">(.*?)</section>',
                                 src, re.S):
        for raw in re.findall(r'class="spot-name">(.*?)</span>', block, re.S):
            out.append((sec, html.unescape(re.sub(r'<[^>]+>', '', raw)).strip()))
    return src, out


def draw(fr, ways, box=None, label=''):
    """One map. `box` is a second frame to outline on it -- the locator."""
    layers = ['<rect width="%d" height="%d" fill="%s"/>' % (fr.pxw, fr.pxh, INK)]
    for cls, w in WATER:
        d, n = lines_path(fr, ways, 'waterway', cls)
        if n:
            layers.append(stroke(RIVER, w, d))
    for cls, w, colour in ROADS:
        d, n = lines_path(fr, ways, 'highway', cls)
        if n:
            layers.append(stroke(colour, w, d))
    if box is not None:
        # The locator. Drawn into the SVG rather than laid over it in HTML: it
        # is part of the picture, and it has to scale with it exactly.
        x0, y0 = fr.px(box.w, box.n)
        x1, y1 = fr.px(box.e, box.s)
        layers.append('<rect x="%.1f" y="%.1f" width="%.1f" height="%.1f" fill="none" '
                      'stroke="%s" stroke-width="%d" rx="%d"/>'
                      % (x0, y0, x1-x0, y1-y0, ACCENT, max(3, fr.pxw//140), fr.pxw//180))
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
            'role="img" aria-label="%s">\n%s\n</svg>\n'
            % (fr.pxw, fr.pxh, label, '\n'.join(layers)))


def pin_block(fr, places, skip_inside=None):
    """The pins for one frame. Numbering is the page's, not the frame's."""
    out = []
    for i, (sec, name) in enumerate(places, start=1):
        if name not in COORDS:
            continue
        lat, lon = COORDS[name]
        if not fr.holds(lat, lon):
            continue
        # A place shown on the closer map is not repeated on the wider one:
        # nine discs on top of each other is a red blob, not a map.
        if skip_inside is not None and skip_inside.holds(lat, lon):
            continue
        x, y = fr.px(lon, lat)
        top = y/fr.pxh*100
        cls = 'map-pin map-pin-low' if top < FLIP_ABOVE else 'map-pin'
        out.append('<a class="%s" href="#%s" style="left:%.2f%%;top:%.2f%%">%d'
                   '<span class="map-tip">%s</span></a>'
                   % (cls, sec, x/fr.pxw*100, top, i, html.escape(name)))
    return out


def main():
    print('city   %d x %d px, %.3f:1' % (CITY.pxw, CITY.pxh, CITY.pxw/CITY.pxh))
    print('centre %d x %d px, %.3f:1' % (CENTRE.pxw, CENTRE.pxh, CENTRE.pxw/CENTRE.pxh))
    ways = load(INPUTS)

    open(OUT_SVG, 'w').write(draw(
        CITY, ways, box=CENTRE,
        label='Sheffield: its rivers and main roads, with the city centre marked'))
    centre_svg = OUT_SVG.replace('-map.svg', '-centre.svg')
    open(centre_svg, 'w').write(draw(
        CENTRE, ways, label='The centre of Sheffield, closer'))

    src, places = read_places(PAGE)
    on_page = set(n for _, n in places)
    for _, n in places:
        if n not in COORDS and not n.startswith('PLACEHOLDER'):
            print('  no coordinate for "%s"' % n)
    for n in COORDS:
        if n not in on_page:
            print('  UNUSED coordinate "%s" -- renamed or removed?' % n)
    for name, (lat, lon) in COORDS.items():
        if not CITY.holds(lat, lon):
            print('  WARNING %s falls outside the city frame' % name)

    blocks = {'CITY':   pin_block(CITY, places, skip_inside=CENTRE),
              'CENTRE': pin_block(CENTRE, places)}
    for key, pins in blocks.items():
        begin, end = FENCES[key]
        block = begin + '\n' + '\n'.join(pins) + '\n' + end
        if begin in src and end in src:
            src = re.sub(re.escape(begin) + r'.*?' + re.escape(end),
                         lambda _: block, src, flags=re.S)
        else:
            print('  fence %s missing from the page' % key)
    open(PAGE, 'w').write(src)
    print('%s: %d on the city, %d on the centre'
          % (PAGE, len(blocks['CITY']), len(blocks['CENTRE'])))


if __name__ == '__main__':
    main()
