#!/usr/bin/env python3
"""Build a city map from OpenStreetMap data, and write its pins into the page.

    python3 build_city_map.py naples.geojson naples.html naples-map.svg

The GeoJSON comes from overpass-turbo.eu. The query, for a given bounding box:

    [out:json][timeout:90];
    (
      way["natural"="coastline"](S,W,N,E);
      way["waterway"="river"](S,W,N,E);
      way["highway"~"^(motorway|trunk|primary|secondary|tertiary|residential)$"](S,W,N,E);
    );
    out geom;

WHY THIS REPLACED THE TRACED POSTER
The first version of this map was traced out of a printed poster. It worked,
but every step of it was found by hand for that one picture: the crop, the ink
threshold, the opening radius that told roads from water, and three coastal
landmarks used to fit a georeference by eye. None of that transfers to a second
city, and the fit was good to only about 200 metres -- enough to put a seafront
address out to sea.

Data arrives already positioned, so the whole fitting step is gone. It also
carries roads and rivers, which matters more for the next city than for this
one: Naples is legible from its bay, but somewhere inland would be a black
rectangle without streets in it.

WHAT IS STILL RASTERISED, AND WHY
The land is filled as a bitmap and then traced, rather than assembled from the
coastline ways directly. OSM coastline is a set of open lines with land on the
left, so building polygons from them means honouring each way's direction and
walking the frame edge to close it -- and it fails whenever a way starts or
ends mid-frame, which is normal in an extract. Flooding the water from a point
known to be at sea gets the same answer and cannot fail that way.
"""

import sys, re, math, html, json
import numpy as np, cv2

GEOJSON = sys.argv[1] if len(sys.argv) > 1 else 'naples.geojson'
PAGE    = sys.argv[2] if len(sys.argv) > 2 else 'naples.html'
OUT_SVG = sys.argv[3] if len(sys.argv) > 3 else 'naples-map.svg'

# The frame, in coordinates. This is the crop the traced version ended up with,
# so the shape stays the one that was chosen. The height follows from the width
# and the projection; do not set it.
W_DEG, E_DEG = 14.20056, 14.28748
S_DEG, N_DEG = 40.81980, 40.86250
PXW = 1800
SEA_SEED = (14.2450, 40.8215)      # any point that is unambiguously water

INK   = '#000000'                  # --ink
# Two greys, not one. The through-routes are structure and want to be read;
# the small streets are texture and want to be felt. Giving them the same value
# and only a different width turns the dense quarters into a single grey wash,
# which is what a full network usually looks like at this size.
ROAD_MAJOR = '#5f5f5f'
ROAD_MINOR = '#3a3a3a'
RIVER      = '#f4f1ea'             # --band, i.e. read as water

# Rendered thinnest first so the big roads cross over the small ones.
ROADS = [('residential', 1.6, ROAD_MINOR),
         ('tertiary',    2.4, ROAD_MINOR),
         ('secondary',   3.5, ROAD_MAJOR),
         ('primary',     5.0, ROAD_MAJOR),
         ('trunk',       6.0, ROAD_MAJOR),
         ('motorway',    7.0, ROAD_MAJOR)]

# A tooltip opens upwards. For a pin near the top of the frame that puts it off
# the map, so those few open downwards instead.
FLIP_ABOVE = 18                    # per cent of the frame height

SIMPLIFY = 1.2                     # px. Below a pixel at display size, so it
                                   # removes points rather than detail.

BEGIN = '<!-- PINS: generated by build_city_map.py, do not edit by hand -->'
END   = '<!-- /PINS -->'

COORDS = {
    'Pizzeria Starit\u00e0':    (40.85606905193841, 14.24639434232922),
    'Pizzeria Salvo':           (40.83358732183927, 14.23892516626797),
    '50 Kal\u00f2':             (40.82851792749763, 14.22035942393942),
    'Concettina ai Tre Santi':  (40.85761176336574, 14.25213894232926),
    '10 Diego Vitagliano':      (40.83243992567843, 14.24946107268464),
    'Osteria Della Mattonella': (40.83677267808366, 14.24467297921869),
    'Umberto 1916':             (40.83494458496786, 14.24177899260066),
    'Cuccuma Caff\u00e8':       (40.84529161321004, 14.25292413077910),
    'Salumeria Malinconico':    (40.85001185558353, 14.24193254483264),
    'Tandem Spaccanapoli':      (40.84811817913380, 14.25440837551848),
    'Alimentari Coscia':        (40.85011481101426, 14.25454371414681),
    'Caff\u00e8 Sansone':       (40.83971517015687, 14.24116120011191),
    'Ventimetriquadri':         (40.84566145080303, 14.23193911414681),
    'Mexico Piazza Dante':      (40.84957479671078, 14.25009168716119),
    'Il Gelato Mennella':       (40.84458465848114, 14.25633294781740),
    'Gay Odin':                 (40.84839079726274, 14.25318496206547),
    'Casa Infante':             (40.83870718185003, 14.24828369785815),
}

merc = lambda lat: math.log(math.tan(math.pi/4 + math.radians(lat)/2))
SX = PXW / (math.radians(E_DEG) - math.radians(W_DEG))
PXH = int(round(SX * (merc(N_DEG) - merc(S_DEG))))
to_px = lambda lon, lat: (SX*(math.radians(lon) - math.radians(W_DEG)),
                          SX*(merc(N_DEG) - merc(lat)))


def rings(feature):
    g = feature['geometry']
    return [g['coordinates']] if g['type'] == 'LineString' else g['coordinates']


def land_mask(coastlines):
    m = np.zeros((PXH, PXW), np.uint8)
    for r in coastlines:
        pts = np.array([to_px(x, y) for x, y in r], np.float32).round().astype(np.int32)
        cv2.polylines(m, [pts], False, 1, 2)
    sea = m.copy()
    cv2.floodFill(sea, np.zeros((PXH+2, PXW+2), np.uint8),
                  tuple(int(v) for v in to_px(*SEA_SEED)), 1)
    return (1 - sea + m).clip(0, 1).astype(np.uint8)


def trace(mask):
    import potrace
    # INVERTED ON PURPOSE. potracer takes the FALSE cells as foreground, so
    # handing it the land traces the water and the map comes out with the bay
    # solid and the city empty. Neither fill-rule nor padding fixes it.
    P = lambda p: (p.x, p.y)
    out = []
    for c in potrace.Bitmap(~mask.astype(bool)).trace(turdsize=40, alphamax=1.0,
                                                      opticurve=True, opttolerance=0.2):
        x, y = P(c.start_point); d = ['M%.1f,%.1f' % (x, y)]
        for s in c:
            ex, ey = P(s.end_point)
            if s.is_corner:
                a, b = P(s.c); d.append('L%.1f,%.1fL%.1f,%.1f' % (a, b, ex, ey))
            else:
                ax, ay = P(s.c1); bx, by = P(s.c2)
                d.append('C%.1f,%.1f %.1f,%.1f %.1f,%.1f' % (ax, ay, bx, by, ex, ey))
        d.append('Z'); out.append(''.join(d))
    return ''.join(out)


def lines_path(features, key, value):
    """One path for every way of a class, simplified and clipped."""
    pad, segs = 40, []
    for f in features:
        if f['properties'].get(key) != value:
            continue
        for r in rings(f):
            pts = np.array([to_px(x, y) for x, y in r], np.float32)
            if (pts[:, 0].max() < -pad or pts[:, 0].min() > PXW+pad or
                pts[:, 1].max() < -pad or pts[:, 1].min() > PXH+pad):
                continue                       # wholly outside the frame
            pts = cv2.approxPolyDP(pts.reshape(-1, 1, 2), SIMPLIFY, False).reshape(-1, 2)
            if len(pts) < 2:
                continue
            segs.append('M' + 'L'.join('%.1f,%.1f' % (x, y) for x, y in pts))
    return ''.join(segs), len(segs)


def read_places(page):
    src = open(page).read()
    out = []
    for sec, block in re.findall(r'<section class="module" id="(\w+)">(.*?)</section>',
                                 src, re.S):
        for raw in re.findall(r'class="spot-name">(.*?)</span>', block, re.S):
            out.append((sec, html.unescape(re.sub(r'<[^>]+>', '', raw)).strip()))
    return src, out


def main():
    data = json.load(open(GEOJSON))['features']
    print('frame %d x %d px, %.3f:1' % (PXW, PXH, PXW/PXH))

    coast = [r for f in data if f['properties'].get('natural') == 'coastline'
             for r in rings(f)]
    mask = land_mask(coast)
    print('  coastline: %d ways, land %.1f%% of frame' % (len(coast), 100*mask.mean()))

    layers = ['<path fill="%s" fill-rule="evenodd" d="%s"/>' % (INK, trace(mask))]

    river, n = lines_path(data, 'waterway', 'river')
    if n:
        layers.append('<path fill="none" stroke="%s" stroke-width="4" '
                      'stroke-linecap="round" stroke-linejoin="round" d="%s"/>' % (RIVER, river))
        print('  rivers: %d ways' % n)

    for cls, w, colour in ROADS:
        d, n = lines_path(data, 'highway', cls)
        if not n:
            print('  %-11s absent from the export' % cls)
            continue
        layers.append('<path fill="none" stroke="%s" stroke-width="%s" '
                      'stroke-linecap="round" stroke-linejoin="round" d="%s"/>'
                      % (colour, w, d))
        print('  %-11s %4d ways' % (cls, n))

    svg = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" '
           'role="img" aria-label="Naples: the coast and its main roads">\n%s\n</svg>\n'
           % (PXW, PXH, '\n'.join(layers)))
    open(OUT_SVG, 'w').write(svg)
    print('%s: %d kB' % (OUT_SVG, len(svg)//1024))

    # Pins. No anchors and no fitting: the projection above is the projection
    # the data was drawn with, so a coordinate lands where it belongs.
    src, places = read_places(PAGE)
    on_page = set(n for _, n in places)
    for _, n in places:
        if n not in COORDS:
            print('  NO COORDINATE for "%s"' % n)
    for n in COORDS:
        if n not in on_page:
            print('  UNUSED coordinate "%s" -- renamed or removed?' % n)

    pins = []
    for i, (sec, name) in enumerate(places, start=1):
        if name not in COORDS:
            continue
        lat, lon = COORDS[name]
        x, y = to_px(lon, lat)
        if not (0 <= x < PXW and 0 <= y < PXH):
            print('  WARNING %d %s: outside the frame' % (i, name))
        elif not mask[int(y), int(x)]:
            print('  WARNING %d %s: falls in the sea' % (i, name))
        top = y/PXH*100
        cls = 'map-pin map-pin-low' if top < FLIP_ABOVE else 'map-pin'
        pins.append('<a class="%s" href="#%s" style="left:%.2f%%;top:%.2f%%">%d'
                    '<span class="map-tip">%s</span></a>'
                    % (cls, sec, x/PXW*100, top, i, html.escape(name)))

    block = BEGIN + '\n' + '\n'.join(pins) + '\n' + END
    if BEGIN in src and END in src:
        src = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: block, src, flags=re.S)
    else:
        src = re.sub(r'<!-- PINS:.*?/PINS -->', lambda _: block, src, flags=re.S)
    open(PAGE, 'w').write(src)
    print('%s: %d pins written in place.' % (PAGE, len(pins)))


if __name__ == '__main__':
    main()
